### ISSUE TITLE
Miktar belirtmek

### ISSUE THREAD

**Issue by enderahmetyurt** [muratbsts/kaca#1]
Örneğin, dolar satın almak isterken N dolar kaça diye merak edebiliyoruz.

```
$ kaca 5 dolar alırım
```

şeklinde olabilir.

**Comment by muratbsts** [comment]
@enderahmetyurt çok mantıklı. Benim neden aklıma gelmemişti bilmiyorum. Yarına tamamlanmış olur :+1:

**Comment by muratbsts** [comment]
@enderahmetyurt https://github.com/muratbsts/kaca/commit/f517fbabea0dce6a197f527c6b9a847ce25ecf16 ile `kaca 5 dolar alirim` diye sorabilirsin. Hatta artık bitcoin bile sorabilirsin. 🙂
